[project]
name = "neural-sde"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pyrefly>=0.24.2",
    "pytest>=8.4.1",
    "pyyaml>=6.0.2",
    "ruff>=0.12.3",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
    "zarr>=3.1.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["models*", "systems*", "training*", "parameters*"]
exclude = ["tests*", "docs*"]
