"""
This module implements training loss functions for Neural SDE GAN training.
"""
from __future__ import annotations

import torch
from torch import Tensor

# To avoid circular imports, we use a string type hint for CriticNet
# and import it only when type checking.
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from models.neural_sde import CriticNet


def _compute_gradient_penalty(
    critic: "CriticNet", real_trajectories: Tensor, fake_trajectories: Tensor
) -> Tensor:
    """
    Computes the gradient penalty for the critic.

    This enforces the Lipschitz constraint on the critic, which is needed for the
    stability of Wasserstein GANs. The penalty states that the norm of the gradient of the critic should be one.

    Args:
        critic: The critic network.
        real_trajectories: A batch of real trajectories from the dataset.
        fake_trajectories: A batch of fake trajectories from the generator.

    Returns:
        The computed gradient penalty as a scalar tensor.
    """
    batch_size = real_trajectories.size(0)

    # Sample interpolation parameter epsilon from a uniform distribution
    epsilon = torch.rand(batch_size, 1, 1, device=real_trajectories.device)
    epsilon = epsilon.expand_as(real_trajectories)

    # Create interpolated trajectories
    interpolated_trajectories = (
        epsilon * real_trajectories + (1 - epsilon) * fake_trajectories
    )
    interpolated_trajectories.requires_grad_(True)

    # Get critic scores for interpolated trajectories
    interpolated_scores = critic.score(interpolated_trajectories)

    # Compute gradients of the scores with respect to the interpolated trajectories
    gradients = torch.autograd.grad(
        outputs=interpolated_scores,
        inputs=interpolated_trajectories,
        grad_outputs=torch.ones_like(interpolated_scores),
        create_graph=True,
        retain_graph=True,
    )[0]

    # Flatten gradients to compute the norm for each sample in the batch
    gradients = gradients.view(batch_size, -1)

    # Calculate the L2 norm of the gradients
    gradient_norm = torch.sqrt(torch.sum(torch.pow(gradients, 2), dim=1) + 1e-12)

    # Compute the gradient penalty (the deviation from a norm of 1)
    gradient_penalty = torch.mean(torch.pow(gradient_norm - 1.0, 2))

    return gradient_penalty


def wasserstein_critic_loss(
    critic: "CriticNet",
    real_trajectories: Tensor,
    fake_trajectories: Tensor,
    gradient_penalty_weight: float = 10.0,
) -> Tensor:
    """
    Computes the Wasserstein critic loss with a gradient penalty. This is based on work by Gulrajani et al. (2017), arXiv:1704.00028.

    The loss is composed of two parts:
    1. The Wasserstein distance, approximated by the difference in critic scores
       between real and fake data.
    2. A gradient penalty to enforce the 1-Lipschitz constraint on the critic.

    Args:
        critic: The critic network.
        real_trajectories: A batch of real trajectories.
        fake_trajectories: A batch of fake trajectories generated by the generator.
        gradient_penalty_weight: The coefficient for the gradient penalty term, taken to be 10 by default (Gulrajani et al., 2017).

    Returns:
        The total critic loss as a scalar tensor.
    """
    # Get scores for real and fake trajectories from the critic
    real_scores = critic.score(real_trajectories)
    fake_scores = critic.score(fake_trajectories)

    # Approximate the Wasserstein distance
    wasserstein_distance = torch.mean(fake_scores) - torch.mean(real_scores)

    # Calculate the gradient penalty
    gradient_penalty = _compute_gradient_penalty(
        critic, real_trajectories, fake_trajectories
    )

    # Combine the Wasserstein distance and the gradient penalty
    loss = wasserstein_distance + gradient_penalty_weight * gradient_penalty
    return loss
