_wandb:
    value:
        cli_version: 0.22.3
        e:
            9o99xwgvkv19qr4cqw4yctawpr9pcc7c:
                codePath: examples/nanorings.py
                codePathLocal: examples/nanorings.py
                email: me@jackg.co
                executable: /Users/jack/Library/Mobile Documents/com~apple~CloudDocs/Research/neural-sde/.venv/bin/python3
                git:
                    commit: a6b7f9ebf9560ec0d6d69b594c61be55431311cf
                    remote: git@github.com:Neuromorphic-Spintronics/neural-sde.git
                host: eip-autoe89f80cce21c.ddns.shef.ac.uk
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/jack/Library/Mobile Documents/com~apple~CloudDocs/Research/neural-sde/examples/nanorings.py
                python: CPython 3.13.3
                root: /Users/jack/Library/Mobile Documents/com~apple~CloudDocs/Research/neural-sde
                startedAt: "2025-11-12T12:35:55.120304Z"
                writerId: 9o99xwgvkv19qr4cqw4yctawpr9pcc7c
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
            "4": 3.13.3
            "5": 0.22.3
            "10":
                - 20
            "12": 0.22.3
            "13": darwin-arm64
batch_size:
    value: 128
critic_window_size:
    value: 64
gan_batch_size:
    value: 128
moment_matching_enabled:
    value: true
moment_matching_weight:
    value: 100
number_of_epochs:
    value: 4096
number_of_gan_epochs:
    value: 2048
output_directory:
    value: examples/output/nanorings_d5a1d216
sde_l1_weight:
    value: 1
train_ode_with_sde:
    value: true
